In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('D:\\Ethereum project\\Data Processing\\1-Merge.csv', parse_dates=['Date'], index_col='Date')
df

,REF,ADA_Price(USDT),ADA_Volume(USDT),ADA_Tradecount,BNB_Price(USDT),BNB_Volume(USDT),BNB_Tradecount,BTC_Price(USDT),BTC_Volume(USDT),BTC_Tradecount,...,Uncles,verified-contracts,USD_EURO,USD_YUAN,WGS7YR,Gold_Price,NASDAQ_Ind,OIL_PRICE,GOOGLE_TREND,TWEETS
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,434,0,NaN,NaN,2.10,NaN,NaN,NaN,1.14,NaN
2016-01-02,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,505,0,NaN,NaN,NaN,NaN,NaN,NaN,1.50,NaN
2016-01-03,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,529,0,NaN,NaN,NaN,NaN,NaN,NaN,1.56,NaN
2016-01-04,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,516,0,0.925669,6.5338,NaN,1072.70,130.71,31.79,1.77,NaN
2016-01-05,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,583,0,0.930839,6.5219,NaN,1078.00,130.85,31.21,1.20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,0,1.58425,817239543.2,1626406.0,349.325,5253443.362,1933829.0,37096.740,135377.62970,2659178.0,...,319,293,0.820075,6.3674,1.25,1892.45,279.08,68.20,43.00,33173.0
2021-05-29,0,1.45810,576104659.3,1181284.0,316.950,3764083.292,1390377.0,35133.470,112663.09270,2169643.0,...,337,195,NaN,NaN,NaN,NaN,NaN,NaN,41.00,28110.0
2021-05-30,0,1.48930,764079031.7,1702526.0,315.375,3739673.114,1408477.0,35123.210,73535.38697,1559892.0,...,342,262,NaN,NaN,NaN,NaN,NaN,NaN,42.00,18637.0
2021-05-31,0,1.65620,600116070.9,1460887.0,339.440,4110136.874,1491701.0,36447.535,94160.73529,1896359.0,...,309,326,NaN,NaN,NaN,NaN,NaN,68.53,40.00,20195.0
2021-06-01,0,1.73695,530252586.9,1214297.0,357.880,3652280.692,1433677.0,36973.455,81234.66377,1760417.0,...,286,399,0.816927,6.3796,NaN,1907.70,281.52,69.01,NaN,18813.0

In [3]:
df.loc[:,'ADA_Price(USDT)':'XRP_Tradecount']=df.loc[:,'ADA_Price(USDT)':'XRP_Tradecount'].fillna(0)
df

,REF,ADA_Price(USDT),ADA_Volume(USDT),ADA_Tradecount,BNB_Price(USDT),BNB_Volume(USDT),BNB_Tradecount,BTC_Price(USDT),BTC_Volume(USDT),BTC_Tradecount,...,Uncles,verified-contracts,USD_EURO,USD_YUAN,WGS7YR,Gold_Price,NASDAQ_Ind,OIL_PRICE,GOOGLE_TREND,TWEETS
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,0,0.00000,0.0,0.0,0.000,0.000,0.0,0.000,0.00000,0.0,...,434,0,NaN,NaN,2.10,NaN,NaN,NaN,1.14,NaN
2016-01-02,0,0.00000,0.0,0.0,0.000,0.000,0.0,0.000,0.00000,0.0,...,505,0,NaN,NaN,NaN,NaN,NaN,NaN,1.50,NaN
2016-01-03,0,0.00000,0.0,0.0,0.000,0.000,0.0,0.000,0.00000,0.0,...,529,0,NaN,NaN,NaN,NaN,NaN,NaN,1.56,NaN
2016-01-04,0,0.00000,0.0,0.0,0.000,0.000,0.0,0.000,0.00000,0.0,...,516,0,0.925669,6.5338,NaN,1072.70,130.71,31.79,1.77,NaN
2016-01-05,0,0.00000,0.0,0.0,0.000,0.000,0.0,0.000,0.00000,0.0,...,583,0,0.930839,6.5219,NaN,1078.00,130.85,31.21,1.20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-28,0,1.58425,817239543.2,1626406.0,349.325,5253443.362,1933829.0,37096.740,135377.62970,2659178.0,...,319,293,0.820075,6.3674,1.25,1892.45,279.08,68.20,43.00,33173.0
2021-05-29,0,1.45810,576104659.3,1181284.0,316.950,3764083.292,1390377.0,35133.470,112663.09270,2169643.0,...,337,195,NaN,NaN,NaN,NaN,NaN,NaN,41.00,28110.0
2021-05-30,0,1.48930,764079031.7,1702526.0,315.375,3739673.114,1408477.0,35123.210,73535.38697,1559892.0,...,342,262,NaN,NaN,NaN,NaN,NaN,NaN,42.00,18637.0
2021-05-31,0,1.65620,600116070.9,1460887.0,339.440,4110136.874,1491701.0,36447.535,94160.73529,1896359.0,...,309,326,NaN,NaN,NaN,NaN,NaN,68.53,40.00,20195.0
2021-06-01,0,1.73695,530252586.9,1214297.0,357.880,3652280.692,1433677.0,36973.455,81234.66377,1760417.0,...,286,399,0.816927,6.3796,NaN,1907.70,281.52,69.01,NaN,18813.0

In [4]:
df.loc[:,'AddressCount':'verified-contracts'].isnull().sum()

AddressCount                                     0
AverageDailyTransactionFee                       0
AvgGasPrice                                      0
BlockCountRewards                                0
BlockDifficulty                                  0
BlockReward                                      0
BlockSize                                        0
BlockTime                                        0
DailyActiveERC20Address                          0
DailyActiveEthAddress                            0
EnsRegistrations                               488
EtherPrice                                       0
GasLimit                                         0
GasUsed                                          0
MarketCap                                        0
NetworkHash                                      0
NetworkUtilization                               0
PendingQueue                                  1986
tokenerc-20txns-ERC20 daily token transfer       0
TransactionFee                                   0
TxGrowth- Ethereum daily transactions            0
Uncles                                           0
verified-contracts                               0
dtype: int64

In [5]:
df=df.drop(["PendingQueue"], axis=1)

In [6]:
df["EnsRegistrations"]=df["EnsRegistrations"].fillna(0)

In [7]:
df.loc[:,'USD_EURO':'TWEETS'].isnull().sum()

USD_EURO         628
USD_YUAN         628
WGS7YR          1703
Gold_Price       611
NASDAQ_Ind       617
OIL_PRICE        585
GOOGLE_TREND       1
TWEETS           130
dtype: int64

In [8]:
df["WGS7YR"]=df["WGS7YR"].fillna(method='bfill')

In [9]:
df["TWEETS"]=df["TWEETS"].fillna(0)

In [10]:
df.loc[:,'USD_EURO':'TWEETS']=df.loc[:,'USD_EURO':'TWEETS'].fillna(method='ffill')

In [11]:
df.loc[:,'USD_EURO':'TWEETS']=df.loc[:,'USD_EURO':'TWEETS'].fillna(method='bfill')
df.loc[:,'USD_EURO':'TWEETS'].isnull().sum()

USD_EURO        0
USD_YUAN        0
WGS7YR          0
Gold_Price      0
NASDAQ_Ind      0
OIL_PRICE       0
GOOGLE_TREND    0
TWEETS          0
dtype: int64

In [12]:
df.loc[:,'ADA_Price(USDT)':'XRP_Tradecount'].isnull().sum()

ADA_Price(USDT)      0
ADA_Volume(USDT)     0
ADA_Tradecount       0
BNB_Price(USDT)      0
BNB_Volume(USDT)     0
BNB_Tradecount       0
BTC_Price(USDT)      0
BTC_Volume(USDT)     0
BTC_Tradecount       0
DOT_Price(USDT)      0
DOT_Volume(USDT)     0
DOT_Tradecount       0
EOS_Price(USDT)      0
EOS_Volume(USDT)     0
EOS_Tradecount       0
ETC_Price(USDT)      0
ETC_Volume(USDT)     0
ETC_Tradecount       0
ETH_Price(USDT)      0
ETH_Volume(USDT)     0
ETH_Tradecount       0
LINK_Price(USDT)     0
LINK_Volume(USDT)    0
LINK_Tradecount      0
LTC_Price(USDT)      0
LTC_Volume(USDT)     0
LTC_Tradecount       0
SOL_Price(USDT)      0
SOL_Volume(USDT)     0
SOL_Tradecount       0
TRX_Price(USDT)      0
TRX_Volume(USDT)     0
TRX_Tradecount       0
XLM_Price(USDT)      0
XLM_Volume(USDT)     0
XLM_Tradecount       0
XRP_Price(USDT)      0
XRP_Volume(USDT)     0
XRP_Tradecount       0
dtype: int64

In [13]:
print(list(df.isnull().sum()))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [14]:
df=df.drop(["REF"], axis=1)

In [15]:
df=df.drop(["ETH_Price(USDT)"], axis=1)

In [16]:
df.to_csv('2-Remove_null.csv')